{{- if and (not (default .Values.global.existingSecret .Values.existingSecret)) (ne (default .Values.global.secretlink.enabled .Values.secretlink.enabled) true) }}
########################################################################
# OpenText PowerDocs Kubernetes Secrets
########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
  OTPD_ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc }}
  OTPD_USER_PASSWORD: {{ .Values.userPassword | b64enc }}
  OTPD_MONITOR_USER_PASSWORD: {{ .Values.monitorUserPassword | b64enc }}
  OTPD_API_USER_PASSWORD: {{ .Values.apiUserPassword | b64enc }}
  {{- if .Values.technicalUserPassword }}
  OTPD_TECHNICAL_USER_PASSWORD: {{ .Values.technicalUserPassword | b64enc }}
  {{- end }}
  OTDS_PASSWORD: {{ .Values.otds.password | b64enc }}
  OTCS_ADMIN_PASSWORD: {{ .Values.otcs.password | b64enc }}
  OTPD_DB_ADMIN_PASSWORD: {{ .Values.database.adminPassword | b64enc }}
  OTPD_DB_PASSWORD: {{ .Values.database.password | b64enc }}
  {{- if .Values.emailServerSettings.password }}
  EMAIL_SERVER_PASSWORD: {{ .Values.emailServerSettings.password | b64enc }}
  {{- end }}
---
{{- end }}