{{- if eq .Values.config.documentStorage.type "efs" }}
########################################################################
# EFS persistent volume claim for OpenText Content Server
# There are matching volume mount and volume '{{ .Chart.Name }}-efs'
# in the file otcs-statefulsets.yaml
########################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-efs
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
{{- if or .Values.global.storageClassNameNFS .Values.config.documentStorage.efsStorageClassName }}
  storageClassName: {{ default .Values.global.storageClassNameNFS .Values.config.documentStorage.efsStorageClassName | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.config.documentStorage.efsStorage }}
---
{{- end }}
{{- if eq .Values.config.search.sharedSearch.enabled true }}
########################################################################
# Search shared persistent volume claim for OpenText Content Server
# This must use a RWX (ReadWriteMany) storage class
# There is a matching volumeClaimTemplate
# 'otcs-shared-admin-index' in the otcs StatefulSet.
# otcs-statefulsets.yaml
########################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-admin-index-shared
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ default .Values.global.storageClassNameNFS .Values.config.search.sharedSearch.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.config.search.sharedSearch.storage }}
---
{{- end }}
{{- if eq .Values.config.storageProviderCache.enabled true }}
########################################################################
# Storage Provider Cache persistent volume claim for OpenText Content Server
# This must use a RWX (ReadWriteMany) storage class
# There is a matching volumeClaimTemplate
# 'otcs-storageProviderCache' in the otcs StatefulSet.
# otcs-statefulsets.yaml
########################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-storageprovidercache
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ default .Values.global.storageClassNameNFS .Values.config.storageProviderCache.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.config.storageProviderCache.storage }}
---
{{- end }}

{{- if and (eq .Values.objectimporter.enabled true) (not (lookup "v1" "PersistentVolumeClaim" .Release.Namespace "sftp-volume")) }}
########################################################################
# Object importer persistent volume claim for OpenText Content Server
# There is a volume 
# 'otcs-sftp-volume' in the otcs StatefulSet.
# otcs-statefulsets.yaml
########################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-volume
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
    {{- if .Values.pvc.sftpVolume.labels }}
    {{- range .Values.pvc.sftpVolume.labels }}
    {{ . }}
    {{- end }}
    {{- end }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ default .Values.global.storageClassNameNFS .Values.storageClassNameNFS }}
  resources:
    requests:
      storage: {{ .Values.objectimporter.storage }}
---
{{- end }}

{{- if eq .Values.config.contentProtection.enabled true }}
########################################################################
# contentprotection persistent volume claim for OpenText Content Server
# There is a volume 'otcs-contentprotection' in the otcs StatefulSet(otcs-statefulsets.yaml)
########################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-contentprotection
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
    {{- if .Values.pvc.contentProtection.labels }}
    {{- range .Values.pvc.contentProtection.labels }}
    {{ . }}
    {{- end }}
    {{- end }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ default .Values.global.storageClassNameNFS .Values.storageClassNameNFS }}
  resources:
    requests:
      storage: {{ .Values.config.contentProtection.storage }}
---
{{- end }}

