apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: myrelease
    meta.helm.sh/release-namespace: ecm
  creationTimestamp: "2025-09-13T10:09:23Z"
  generation: 1
  labels:
    app.kubernetes.io/component: otcs-frontend
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otcs
    app.kubernetes.io/version: 25.3.0
    helm.sh/chart: otcs-25.3.0
  name: otcs-frontend
  namespace: ecm
  resourceVersion: "449347"
  uid: 899e63cf-badb-4418-aae1-a36d24921223
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: otcs-frontend
      app.kubernetes.io/instance: myrelease
  serviceName: otcs-frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: otcs-frontend
        app.kubernetes.io/instance: myrelease
    spec:
      containers:
      - command:
        - sh
        - -c
        - until [ "$(curl -s -w '%{http_code}' -o /dev/null http://localhost:8000/readyz)"
          -eq 200 ]; do echo "Waiting for Kubernetes API to be ready"; sleep 10; done;
          /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
        env:
        - name: OTCS_BACKEND_SEARCH_REPLICAS
          value: "1"
        - name: OTCS_FRONTEND_REPLICAS
          value: "1"
        - name: OTCS_TYPE
          value: secondary
        - name: OTCS_CONTAINER_LOG_LEVEL
          value: DEBUG
        - name: OTCS_ROLE
          value: frontend
        - name: OTDS_SERVICE_NAME
          value: otds
        - name: SHARED_ADDRESS_SPACE_NAT
          value: "false"
        - name: TZ
          value: Asia/Seoul
        - name: PGHOST
          value: ecmsvr25
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          value: postgres
        - name: PGDATABASE
          value: postgres
        - name: MAX_THREAD_LIFESPAN
          value: "10"
        - name: OTXECM_SECRET_NAME
          value: otxecm-default-secrets
        - name: UALEnabled
          value: "false"
        - name: RESTART_AUTOMATION_TIME
          value: "60"
        image: registry.opentext.com/otxecm:25.3.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /opt/opentext/container_files/bash/check_cs_liveness.sh
          failureThreshold: 3
          initialDelaySeconds: 600
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        name: otcs-frontend-container
        ports:
        - containerPort: 2099
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /opt/opentext/container_files/bash/check_cs_readiness.sh
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 6
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/extshared
          name: extshared-storage
        - mountPath: /opt/opentext/extensions
          name: extensions-volume-mount
        - mountPath: /opt/opentext/cs_persist
          name: cs-persist
        - mountPath: /opt/opentext/multifile
          name: otcs-multifile
        - mountPath: /opt/opentext/cs/logs
          name: logs
        - mountPath: /opt/opentext/sftp
          name: sftp-volume
        - mountPath: /opt/opentext/container_files/custom_config/config.yaml
          name: config
          subPath: config.yaml
        - mountPath: /opt/opentext/container_files/custom_config/sp.pem
          name: otcs-archive-cert-configmap
          subPath: sp.pem
      - args:
        - |
          kubectl proxy --port=8000 --address=127.0.0.1 &
          kubectl proxy --port=8000 --address=[::1] &
          wait
        command:
        - sh
        - -c
        image: docker.io/bitnami/kubectl:1.30.4
        imagePullPolicy: IfNotPresent
        name: kubectl-proxy
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      priorityClassName: myrelease-ecm-2
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsUser: 1000
      serviceAccount: otxecm-sa
      serviceAccountName: otxecm-sa
      terminationGracePeriodSeconds: 60
      volumes:
      - name: extshared-storage
        persistentVolumeClaim:
          claimName: otmm-nfs-pvc
      - emptyDir: {}
        name: extensions-volume-mount
      - configMap:
          defaultMode: 420
          name: otcs-frontend-configmap
        name: config
      - configMap:
          defaultMode: 420
          name: otcs-archive-cert-configmap
        name: otcs-archive-cert-configmap
      - name: sftp-volume
        persistentVolumeClaim:
          claimName: sftp-volume
      - emptyDir:
          sizeLimit: 10Gi
        name: otcs-multifile
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: cs-persist
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 6Gi
      storageClassName: otmm-nfs
      volumeMode: Filesystem
    status:
      phase: Pending
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: logs
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: otmm-nfs
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 0
  collisionCount: 0
  currentReplicas: 1
  currentRevision: otcs-frontend-64b958f585
  observedGeneration: 1
  replicas: 1
  updateRevision: otcs-frontend-64b958f585
  updatedReplicas: 1
