global:
  database:
    admin: "postgres"
    hostname: "192.168.100.216"
    ivName: otiv
    password: "Opentext1!"
    port: 5432
  imagePullPolicy: "IfNotPresent"
  imagePullSecret: "regcred"
  imageSource: "registry.opentext.com"
  ingressAnnotations:
    kubernetes.io/ingress.allow-http:               false
    nginx.ingress.kubernetes.io/affinity:           cookie

    nginx.ingress.kubernetes.io/proxy-body-size:    "0"
    nginx.ingress.kubernetes.io/proxy-buffer-size:  "16k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      if ($http_origin) {more_set_headers "Access-Control-Allow-Headers: $sent_http_access_control_allow_headers, X-XHR-Logon, X-Requested-With";}
  ingressClass: nginx
  ingressDomainName: "myubuntu6.hv"
  ingressEnabled: true
  ingressSSLSecret: "xecm-secret"
  masterPassword: "Opentext1!"
  otac:
    enabled: true
  otacc:
    enabled: false
  otacPublicUrl: "https://otac.myubuntu6.hv"
  otcsPublicUrl: "https://otcs.myubuntu6.hv"
  otds:
    enabled: true
  otdsPublicUrl: "https://otds.myubuntu6.hv"
  otiv:
    enabled: true
  otpd:
    enabled: false
  otpdPublicUrl: "https://otpd.myubuntu6.hv"
  resourceRequirements: false
  serviceAccountName: "otxecm-sa"
  storageClassName: "microk8s-hostpath"
  storageClassNameNFS: "microk8s-hostpath"
  timeZone: "Asia/Seoul"

otcs:
  config:
    businessScenariosList:
      - OT-Teamspaces
      - OT-Projects
      - OT-Agreements
      - OT-EAM
      - OT-REALESTATE
      - OT-Procurement
    database:
      adminUsername: "postgres"
      name: "cs"
      useExistingDatabase: true
      username: "postgres"
    defaultAppsInstall: true
    deployBusinessScenarios: true
    extensions:
      enabled: true
      includeManifestInitContainer: false
    otds:
      trustedSites:
        - "https://teams.microsoft.com"
        - "https://otawg.ubuntu-otcm.hv"
    useExtendedECMLicese: false
  containerLogLevel: DEBUG
  contentServerBackendSearch:
    replicas: 1
  contentServerFrontend:
    replicas: 1
  loadAdminSettings:
    enabled: false
  loadLicense:
    enabled: false
    filename: otxecmLicense.lic
  objectimporter:
    enabled: true
  passwords:
    database:
      adminPassword: "Opentext1!"
    scenarioOwnerPassword: "Opentext1!"

otds:
  otdsws:
    cryptKey: "Z2hkN2hyNDBkbWNGcVQ0TA=="
    otdsdb:
      automaticDatabaseCreation:
        dbName: "otdsdb"
        enabled: false
      password: "Opentext1!"
      url: "jdbc:postgresql://192.168.100.216:5432/otdsdb"
      username: "otdsuser"

otiv:
  amqp:
    rabbitmq:
      password: "Opentext1!"

otpd:
  loadLicense: false
  otpdLicense: otpdLicense.lic
  technicalUserPassword: "Opentext1!"
  database:
    hostname: "192.168.100.216"
