{{- if not .Values.justDatabase }}
{{- if not .Values.global.otdsMigration }}
{{- if (include "is.iv" .) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: otiv-delete-lock-secrets
  labels:
    app.kubernetes.io/name: {{ include "brava.name" . }}
    helm.sh/chart: {{ include "brava.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      name: otiv-delete-lock-secrets
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: {{ include "brava.name" . }}
        helm.sh/chart: {{ include "brava.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Never
      serviceAccountName: otiv-delete-secrets-sa
    {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
    {{- end }}
      containers:
      - name: delete-lock-secrets
        image: {{ include "otiv.init.image.path" . }}
        imagePullPolicy: {{ include "image.pull.policy" . }}
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 300m
            memory: 384Mi
        securityContext:
          allowPrivilegeEscalation: false
        command:
          - sh
        args: [ "-c",
                "sleep 1;
                 output=`kubectl delete secrets otiv-resourcel-lock otiv-metis-lock otiv-highlight-lock otiv-publication-lock otiv-publisher-lock`;
                 if [ \"$?\" -eq \"0\" ];
                 then
                     echo \"Secrets deleted; Continuing.\";
                 else
                     echo \"Secrets didn't exist; Continuing.\";
                 fi;" ]
{{- end }}
{{- end }}
{{- end }}
