{{- if and .Values.global.otivSecretProviderClass.enabled (eq .Values.global.otivSecretProviderClass.provider "aws") }}
{{- $ivArn :=    default .Values.global.otivSecretProviderClass.objectName .Values.global.otivSecretProviderClass.ivObjectName -}}
{{- $dbArn :=    default .Values.global.otivSecretProviderClass.objectName .Values.global.otivSecretProviderClass.dbObjectName -}}
{{- $otdsArn :=  default .Values.global.otivSecretProviderClass.objectName .Values.global.otivSecretProviderClass.otdsObjectName -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: otiv-base-spc
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-10"
spec:
  provider: aws
  parameters:
    {{- if .Values.global.otivSecretProviderClass.region }}
    region: {{- .Values.global.otivSecretProviderClass.region }}
    {{- end }}
    {{- if .Values.global.otivSecretProviderClass.usePodIdentity }}
    usePodIdentity: "{{- .Values.global.otivSecretProviderClass.usePodIdentity }}"
    {{- end }}
    objects: |
      - objectName: {{ $ivArn }}
        objectType: secretsmanager
        objectAlias: iv
        jmesPath:
          - path: "\"{{ default .Values.global.amqp.pwdKey .Values.global.otivSecretProviderClass.amqpKey }}\""
            objectAlias: amqp
          - path: "\"{{ default .Values.publication.clientSecretKey .Values.global.otivSecretProviderClass.publicationKey }}\""
            objectAlias: publication
          - path: "\"{{ default .Values.publication.monitoring.clientSecretKey .Values.global.otivSecretProviderClass.monitoringKey }}\""
            objectAlias: monitoring
          - path: "\"{{ default .Values.publisher.clientSecretKey .Values.global.otivSecretProviderClass.publisherKey }}\""
            objectAlias: publisher
          - path: "\"{{ default .Values.highlight.clientSecretKey .Values.global.otivSecretProviderClass.highlightKey }}\""
            objectAlias: highlight
{{- if and (eq $ivArn $dbArn) (eq $ivArn $otdsArn) }}
          - path: "\"{{ default .Values.global.dbSecretKey .Values.global.otivSecretProviderClass.dbKey }}\""
            objectAlias: db
          - path: "\"{{ default .Values.global.ivDbSecretKey .Values.global.otivSecretProviderClass.ivDbKey }}\""
            objectAlias: ivDb
          - path: "\"{{ default .Values.global.otdsSecretKey .Values.global.otivSecretProviderClass.otdsKey }}\""
            objectAlias: otds
{{- else if eq $ivArn $dbArn }}
          - path: "\"{{ default .Values.global.dbSecretKey .Values.global.otivSecretProviderClass.dbKey }}\""
            objectAlias: db
          - path: "\"{{ default .Values.global.ivDbSecretKey .Values.global.otivSecretProviderClass.ivDbKey }}\""
            objectAlias: ivDb
      - objectName: {{ $otdsArn }}
        objectType: secretsmanager
        objectAlias: otdsAll
        jmesPath:
          - path: "\"{{ default .Values.global.otdsSecretKey .Values.global.otivSecretProviderClass.otdsKey }}\""
            objectAlias: otds
{{- else if eq $ivArn $otdsArn }}
          - path: "\"{{ default .Values.global.otdsSecretKey .Values.global.otivSecretProviderClass.otdsKey }}\""
            objectAlias: otds
      - objectName: {{ $dbArn }}
        objectType: secretsmanager
        objectAlias: dbAll
        jmesPath:
          - path: "\"{{ default .Values.global.dbSecretKey .Values.global.otivSecretProviderClass.dbKey }}\""
            objectAlias: db
          - path: "\"{{ default .Values.global.ivDbSecretKey .Values.global.otivSecretProviderClass.ivDbKey }}\""
            objectAlias: ivDb
{{- else if eq $dbArn $otdsArn }}
      - objectName: {{ $dbArn }}
        objectType: secretsmanager
        objectAlias: dbOtds
        jmesPath:
          - path: "\"{{ default .Values.global.dbSecretKey .Values.global.otivSecretProviderClass.dbKey }}\""
            objectAlias: db
          - path: "\"{{ default .Values.global.ivDbSecretKey .Values.global.otivSecretProviderClass.ivDbKey }}\""
            objectAlias: ivDb
          - path: "\"{{ default .Values.global.otdsSecretKey .Values.global.otivSecretProviderClass.otdsKey }}\""
            objectAlias: otds
{{- else }}
      - objectName: {{ $dbArn }}
        objectType: secretsmanager
        objectAlias: dbAll
        jmesPath:
          - path: "\"{{ default .Values.global.dbSecretKey .Values.global.otivSecretProviderClass.dbKey }}\""
            objectAlias: db
          - path: "\"{{ default .Values.global.ivDbSecretKey .Values.global.otivSecretProviderClass.ivDbKey }}\""
            objectAlias: ivDb
      - objectName: {{ $otdsArn }}
        objectType: secretsmanager
        objectAlias: otdsAll
        jmesPath:
          - path: "\"{{ default .Values.global.otdsSecretKey .Values.global.otivSecretProviderClass.otdsKey }}\""
            objectAlias: otds
{{- end }}
  secretObjects:
    - secretName: otiv-spc-secrets
      type: Opaque
      data:
        - objectName: otds
          key: {{ .Values.global.otdsSecretKey }}
        - objectName: db
          key: {{ .Values.global.dbSecretKey }}
        - objectName: ivDb
          key: {{ .Values.global.ivDbSecretKey }}
        - objectName: amqp
          key: {{ .Values.global.amqp.pwdKey }}
        - objectName: publication
          key: {{ .Values.publication.clientSecretKey }}
        - objectName: monitoring
          key: {{ .Values.publication.monitoring.clientSecretKey }}
        - objectName: publisher
          key: {{ .Values.publisher.clientSecretKey }}
        - objectName: highlight
          key: {{ .Values.highlight.clientSecretKey }}
{{- end }}
{{- if and .Values.global.otivSecretProviderClassCerts.enabled (eq .Values.global.otivSecretProviderClass.provider "aws") }}
---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: otiv-spc-certs
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-10"
spec:
  provider: aws
  parameters:
    {{- if .Values.global.otivSecretProviderClassCerts.region }}
    region: {{- .Values.global.otivSecretProviderClassCerts.region }}
    {{- end }}
    objects: |
      {{- range .Values.global.otivSecretProviderClassCerts.secrets }}
      - objectName: "{{ .name }}"
        objectType: "secretsmanager"
        objectAlias: "{{ .certFileName }}"
    {{- end }}
{{- end }}

