{{- if not .Values.justDatabase }}
{{- if not .Values.global.otdsMigration }}
{{- if (include "is.iv" .) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: stop-transformation-pods
  labels:
    app.kubernetes.io/name: {{ include "brava.name" . }}
    helm.sh/chart: {{ include "brava.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      name: stop-transformation-pods
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: {{ include "brava.name" . }}
        helm.sh/chart: {{ include "brava.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Never
      serviceAccountName: otiv-deployment-sa
    {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
    {{- end }}
      containers:
      - name: stop-transformation-pods
        image: {{ include "otiv.init.image.path" . }}
        imagePullPolicy: {{ include "image.pull.policy" . }}
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 300m
            memory: 384Mi
        securityContext:
          allowPrivilegeEscalation: false
        env:
        {{- if .Values.global.stopLegacyOtdsForUpgrade }}
          - name: STOP_OTDS
            value: 'True'
        {{- end }}
        command:
          - ./scripts/stopPodsForUpgrade.sh
{{- end }}
{{- end }}
{{- end }}
