{{- if not .Values.justDatabase }}
{{- if or (include "is.ocp" .) .Values.global.usingServiceMesh }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: vertx-to-ip
  {{- template "metadata.namespace" . }}
spec:
  hosts:
  - vertx-to-ip.local
  addresses:
  - {{ .Values.global.transformationPodApiIPRanges }}
  exportTo:
  - "."
  ports:
  - number: 5150
    name: tcp-vertx-0
    protocol: TCP
  - number: 5151
    name: tcp-vertx-1
    protocol: TCP
  - number: 5152
    name: tcp-vertx-2
    protocol: TCP
  - number: 5153
    name: tcp-vertx-3
    protocol: TCP
  location: MESH_INTERNAL
  resolution: NONE

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: vertx-to-ip
  {{- template "metadata.namespace" . }}
spec:
  host: vertx-to-ip.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end }}
{{- end }}
