{{- if not (default .Values.global.existingSecret .Values.existingSecret) }}
{{- if not (default .Values.global.secretlink.enabled .Values.secretlink.enabled) }}
########################################################################
# OpenText Archive Center Kubernetes Secrets
########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
  OTDS_PASS: {{ .Values.otds.password | b64enc }}
  TARGET_DB_PASSWORD: {{ .Values.database.password | b64enc }}
  OTAC_DB_ADMIN_PASSWORD: {{ .Values.database.adminPassword | b64enc }}
  {{- if (.Values.encryption.otkm.enabled) }}
  OTAC_OTKM_USER_PASS: {{ required "A valid otkm.userPasswordVal is required!" .Values.encryption.otkm.userPasswordVal | b64enc }}
  {{- end }}
  ## If want to use ILM scenarios 'OTAC_BA_USER_PASSWORD' and 'OTAC_ILM_USER_PASSWORD' fields must be filled mandatorily
  {{- if (.Values.ilm.enabled) }}
  OTAC_BA_USER_PASSWORD: {{ .Values.ilm.users.ba.password | b64enc }}
  OTAC_ACCESS_USER_PASSWORD: {{ .Values.ilm.users.access.password | b64enc }}
  OTAC_ILM_USER_PASSWORD: {{ .Values.ilm.users.ilm.password | b64enc }}
  OTAC_MY_USER_PASSWORD: {{ .Values.ilm.users.my.password | b64enc }}
  OTAC_CMIS_SYSTEM_PASSWORD: {{ .Values.ilm.users.systemPassword | b64enc }}
  {{- end }}
  {{- if .Values.standardUserPasswords.dsadmin }}
  OTAC_DSADMIN_PASSWORD: {{ .Values.standardUserPasswords.dsadmin | b64enc }}
  {{- end}}
  {{- if .Values.standardUserPasswords.dpadmin }}
  OTAC_DPADMIN_PASSWORD: {{ .Values.standardUserPasswords.dpadmin | b64enc }}
  {{- end}}
  {{- if .Values.standardUserPasswords.dpuser }}
  OTAC_DPUSER_PASSWORD: {{ .Values.standardUserPasswords.dpuser | b64enc }}
  {{- end}}
  {{- if and (.Values.config.storageDevices.s3.enable) (not (.Values.config.storageDevices.s3.userolebasedauth)) }}
  OTAC_S3_SECRETKEY: {{ required "A valid AWS S3 bucket Seceretkey is required!" .Values.config.storageDevices.s3.secretkey | b64enc }}
  {{- end }}
  {{- if (.Values.config.storageDevices.azure.enable) }}
  OTAC_AZURE_ACCESSKEY: {{ required "A valid Azure Container Accesskey is required!" .Values.config.storageDevices.azure.accesskey | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}

{{- if and .Values.global.masterPassword (not (default .Values.global.secretlink.enabled .Values.secretlink.enabled)) }}
apiVersion: v1
kind: Secret
metadata:
  name: otac-default-password
type: Opaque
data:
  OTAC_DEFAULT_PASSWORD: {{ .Values.global.masterPassword | b64enc | quote }}
{{- end }}
