{{- if and (eq .Values.global.existingSecret "otxecm-default-secrets") (eq .Values.global.secretlink.enabled false) }} 
{{- $secret := lookup "v1" "Secret" .Release.Namespace "otxecm-default-secrets" -}}
########################################################################
# OpenText Content Server Default Kubernetes Secrets
########################################################################
## This is a default secrets file that will be used if you are not creating your own kubernetes secret.
apiVersion: v1
kind: Secret
metadata:
  name: otxecm-default-secrets
  labels:
    app.kubernetes.io/name: {{ default .Release.Name }}
    helm.sh/chart: {{ default .Chart.Name }}
    app.kubernetes.io/managed-by: {{ default .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
data:
{{- if empty .Values.global.masterPassword }}
{{- fail  "\n\nError: Specify the global.masterPassword to populate default secret values. \n"}}
{{- end }}
# Ensure password synchronization between OTCS, OTDS  and OTAC 
{{- if and (eq .Values.global.otcs.enabled true) (eq .Values.global.otds.enabled true) }}
  {{- include "password.synchronization.validation" (dict "value1" .Values.otcs.passwords.adminUserPassword "value2" .Values.otds.otdsws.adminPassword "value3" .Values.global.masterPassword "msg" "otcs.passwords.adminUserPassword and otds.otdsws.adminPassword" ) }}
{{- end }}
{{- if and (eq .Values.global.otac.enabled true) (eq .Values.global.otds.enabled true) }}
  {{- include "password.synchronization.validation" (dict "value1" .Values.otac.otds.password "value2" .Values.otds.otdsws.adminPassword "value3" .Values.global.masterPassword "msg" ".Values.otac.otds.password and .Values.otds.otdsws.adminPassword" ) }}
{{- end }}
{{- if and (eq .Values.global.otcs.enabled true) (eq .Values.global.otac.enabled true) }}
  {{- include "password.synchronization.validation" (dict "value1" .Values.otcs.passwords.adminUserPassword "value2" .Values.otac.otds.password "value3" .Values.global.masterPassword "msg" ".Values.otcs.passwords.adminUserPassword and .Values.otac.otds.password" ) }}
{{- end }}
{{- if and (or (eq .Values.global.otcs.enabled true) (eq .Values.global.otiv.enabled true)) (not (index $secret "ADMIN_USER_PASSWORD")) }}
  ## ADMIN_USER_PASSWORD determines the admin user. This must match OTDS_PASS below.
  ADMIN_USER_PASSWORD: {{ default .Values.global.masterPassword .Values.otcs.passwords.adminUserPassword | b64enc }}
{{- end }}
{{- if eq .Values.global.otcs.enabled true }}
  {{- if not (index $secret "ADMIN_SERVER_PASSWORD")}}
  ## ADMIN_SERVER_PASSWORD determines the admin server password.
  ADMIN_SERVER_PASSWORD: {{ default .Values.global.masterPassword .Values.otcs.passwords.adminServerPassword | b64enc }}
  ## AUTO_SYS_ADMIN_PASSWORD determines the system admin user password.
  AUTO_SYS_ADMIN_PASSWORD: {{ default .Values.global.masterPassword .Values.otcs.passwords.autoSysAdminPassword | b64enc }}
  ## SYS_SUPPORT_PASSWORD is the current password for the sys_support user
  {{- if .Values.otcs.passwords.SysSupportPassword }}
  SYS_SUPPORT_PASSWORD: {{ .Values.otcs.passwords.SysSupportPassword | b64enc }}
  {{- else }}
  SYS_SUPPORT_PASSWORD: {{ default .Values.global.masterPassword .Values.otcs.passwords.adminUserPassword | b64enc }}
  {{- end }}
  ## ALFILTER_USER_PASSWORD determines the ALFilter user password.
  ALFILTER_USER_PASSWORD: {{ default .Values.global.masterPassword .Values.otcs.passwords.alfluserPassword | b64enc }}
  ## DATA_ENCRYPTION_KEY determines the DEK password
  ## The DATA_ENCRYPTION_KEY must be set if secrets are being used
  DATA_ENCRYPTION_KEY: {{ default .Values.global.masterPassword .Values.otcs.passwords.dataEncryptionKey | b64enc }}
  ## OTCS_DB_ADMIN_PASSWORD is the administrative database user (usually postgres for a postgres db or system for an oracle db) password of otcs
  {{- if .Values.otcs.passwords.database.adminPassword }}
  OTCS_DB_ADMIN_PASSWORD: {{ .Values.otcs.passwords.database.adminPassword | b64enc }}
  {{- else }}
  OTCS_DB_ADMIN_PASSWORD: {{ default .Values.global.masterPassword .Values.global.passwords.database.adminPassword | b64enc }}
  {{- end}}
  ## DB_PASSWORD is the password of the user that owns the otcs database
  DB_PASSWORD: {{ default .Values.global.masterPassword .Values.otcs.passwords.database.password | b64enc }}
  {{- end }}
  {{- if and (eq .Values.otcs.config.documentStorage.type "otacc") (not (index $secret "AC_CORE_PASSWORD")) }}
  ## AC_CORE_PASSWORD is the password to log on to the otacc storage
  AC_CORE_PASSWORD: {{ default .Values.global.masterPassword .Values.otcs.passwords.otacc.corePassword | b64enc }}
  {{- end }}
  {{- if and (eq .Values.otcs.config.createAppMonitorUser true) (not (index $secret "APPMONITOR_PASSWORD"))}}
  ## APPMONITOR_PASSWORD is the password of the appmonitor user for Content Server
  APPMONITOR_PASSWORD: {{ default .Values.global.masterPassword .Values.otcs.passwords.appMonitorPassword | b64enc }}
  {{- end }}
  {{- if eq .Values.otcs.config.llm.enabled true }}
  LLM_CLIENT_ID: {{ .Values.otcs.config.llm.clientID | b64enc }}
  LLM_CLIENT_SECRET: {{ default (randAlphaNum 16 | nospace) .Values.otcs.config.llm.clientSecret | b64enc }}
  {{- end }}
  {{- if (not (empty .Values.otcs.passwords.awsSecretKey )) }}
  AWS_SECRET_KEY: {{ .Values.otcs.passwords.awsSecretKey | b64enc }}
  {{- end }}
  {{- if (not (empty .Values.otcs.passwords.awsAccessId )) }}
  AWS_ACCESS_ID: {{ .Values.otcs.passwords.awsAccessId | b64enc }}
  {{- end }}
  {{- if (not (empty .Values.otcs.passwords.proxyPassword ))}}
  PROXY_PASSWORD: {{ .Values.otcs.passwords.proxyPassword | b64enc }}
  {{- end }}
  {{- if (eq .Values.otcs.config.documentStorage.type "gcp") }}
    {{- if (empty .Values.otcs.config.gcpStorageProvider.serviceAccountJson) }}
      {{- fail "\n\nError: .Values.otcs.config.gcpStorageProvider.serviceAccountJson must be set since documentStorage type is gcp.\n" }}
    {{- end }}
  {{- $gcpServiceAccountJson := .Values.otcs.config.gcpStorageProvider.serviceAccountJson }}
  {{- $fileContent := .Files.Get $gcpServiceAccountJson }}
  {{- if not $fileContent }}
  {{- fail (printf "\n\nError: File %s not found or is empty.\n" $gcpServiceAccountJson) }}
  {{- end }}
  gcp_service_account_json: {{ $fileContent | b64enc }}
  {{- end }}
  {{- if eq .Values.otcs.adminPodMonitor.enabled true }}
  PODMONITOR_CLIENT_ID: {{ .Values.otcs.adminPodMonitor.pod_monitor_client_id | b64enc }}
  PODMONITOR_CLIENT_SECRET: {{ default (randAlphaNum 16 | nospace) .Values.otcs.adminPodMonitor.pod_monitor_client_secret | b64enc }}
  {{- end }}
  {{- if and (eq .Values.otcs.config.enableSynchronizedPartition true) (.Values.otcs.passwords.synchronizedPartition.ldapBindPassword) }}
  LDAP_BIND_PASSWORD: {{ .Values.otcs.passwords.synchronizedPartition.ldapBindPassword | b64enc }}
  {{- end }}
{{- end }}
{{- if and (eq .Values.global.otac.enabled true) (not (index $secret "TARGET_DB_PASSWORD") )}}
  ## TARGET_DB_PASSWORD is the password of the user that owns the otac database
  TARGET_DB_PASSWORD: {{ default .Values.global.masterPassword .Values.otac.database.password | b64enc }}
  ## OTAC_DB_ADMIN_PASSWORD is the administrative database user (usually postgres) password of otac
  {{- if .Values.otac.database.adminPassword }}
  OTAC_DB_ADMIN_PASSWORD: {{ .Values.otac.database.adminPassword | b64enc }}
  {{- else }}
  OTAC_DB_ADMIN_PASSWORD: {{ default .Values.global.masterPassword .Values.global.passwords.database.adminPassword | b64enc }}
  {{- end}}
  ## OTDS_PASS is the admin user password for otds. This must match ADMIN_USER_PASSWORD above.
  OTDS_PASS: {{ default .Values.global.masterPassword .Values.otac.otds.password | b64enc }}
  {{- if (.Values.otac.ilm.enabled) }}
  ## OTAC_BA_USER_PASSWORD is the password of the ba user which is added to the otds group <new tenant>
  OTAC_BA_USER_PASSWORD: {{ default .Values.global.masterPassword .Values.otac.ilm.users.ba.password | b64enc }}  
  ## OTAC_ACCESS_USER_PASSWORD is the password of the access user which is added to the otds group <new tenant>_ED
  OTAC_ACCESS_USER_PASSWORD: {{ default .Values.global.masterPassword .Values.otac.ilm.users.access.password | b64enc }}
  ## OTAC_ILM_USER_PASSWORD is the password of the ilm user which is added to the otds group <new tenant>_ILM
  OTAC_ILM_USER_PASSWORD: {{ default .Values.global.masterPassword .Values.otac.ilm.users.ilm.password | b64enc }}
  ## OTAC_MY_USER_PASSWORD is the password of the my user which is added to the otds group <new tenant>_SU
  OTAC_MY_USER_PASSWORD: {{ default .Values.global.masterPassword .Values.otac.ilm.users.my.password | b64enc }}
  ## OTAC_CMIS_SYSTEM_PASSWORD is the password of the system.cmis user which is a technical user for the Application Layer (Archive Center CMIS).
  OTAC_CMIS_SYSTEM_PASSWORD: {{ default .Values.global.masterPassword .Values.otac.ilm.users.systemPassword | b64enc }}
  {{- end}}
  {{- if .Values.otac.standardUserPasswords.dsadmin }}
  OTAC_DSADMIN_PASSWORD: {{ .Values.otac.standardUserPasswords.dsadmin | b64enc }}
  {{- end}}
  {{- if .Values.otac.standardUserPasswords.dpadmin }}
  OTAC_DPADMIN_PASSWORD: {{ .Values.otac.standardUserPasswords.dpadmin | b64enc }}
  {{- end}}
  {{- if .Values.otac.standardUserPasswords.dpuser }}
  OTAC_DPUSER_PASSWORD: {{ .Values.otac.standardUserPasswords.dpuser | b64enc }}
  {{- end}}
  {{- if and (.Values.otac.config.storageDevices.s3.enable) (not (.Values.otac.config.storageDevices.s3.userolebasedauth)) (.Values.otac.config.storageDevices.s3.secretkey) }}
  OTAC_S3_SECRETKEY: {{ .Values.otac.config.storageDevices.s3.secretkey | b64enc }}
  {{- end }}
  {{- if and (.Values.otac.config.storageDevices.azure.enable) (.Values.otac.config.storageDevices.azure.accesskey) }}
  OTAC_AZURE_ACCESSKEY: {{ .Values.otac.config.storageDevices.azure.accesskey | b64enc }}
  {{- end }}
{{- end }}
{{- if and (eq .Values.global.otac.enabled true) (eq .Values.otac.otkm.enabled true) (not (index $secret "OTAC_OTKM_USER_PASS") )}}
  ## OTAC document encryption related configuration
  ## OTAC_OTKM_USER_PASS is the OTDS user password for otac
  OTAC_OTKM_USER_PASS: {{ default .Values.global.masterPassword .Values.otac.encryption.otkm.userPasswordVal | b64enc }}
{{- end }}

{{- if and (eq .Values.global.otacc.enabled true) (not (index $secret "BA_PASSWORD") )}}
  ## BA_PASSWORD is the password of the Business Administrator for Core Archive Connector
  BA_PASSWORD: {{ default .Values.global.masterPassword .Values.otacc.cloud.baPassword | b64enc }}
  ## CONNECTOR_PASSWORD is a password of a technical user used internally by Core Archive Connector
  CONNECTOR_PASSWORD: {{ default .Values.global.masterPassword .Values.otacc.connector.password | b64enc }}
{{- end }} 
{{- if and (eq .Values.global.otds.enabled true) (not (index $secret "OTDS_JAKARTA_PERSISTENCE_JDBC_PASSWORD")) }}
  ## OTDS_JAKARTA_PERSISTENCE_JDBC_USER is the otds database username
  OTDS_JAKARTA_PERSISTENCE_JDBC_USER: {{ .Values.otds.otdsws.otdsdb.username | b64enc }}
  ## OTDS_JAKARTA_PERSISTENCE_JDBC_PASSWORD is the otds database password
  OTDS_JAKARTA_PERSISTENCE_JDBC_PASSWORD: {{ default .Values.global.masterPassword .Values.otds.otdsws.otdsdb.password | b64enc }}
  ## OTDS_DIRECTORY_BOOTSTRAP_INITIALPASSWORD is the admin user password for otds. It must match
  ## the passwords OTDS_PASS, ADMIN_USER_PASSWORD, OTDS_PASSWORD, OTCS_ADMIN_PASSWORD
  OTDS_DIRECTORY_BOOTSTRAP_INITIALPASSWORD: {{ default .Values.global.masterPassword .Values.otds.otdsws.adminPassword | b64enc }}
  ## OTDS_DIRECTORY_BOOTSTRAP_CRfYPTSECRET is used for secure synchronized access to backend DB from
  ## frontend instances. The value is a 16 character ASCII string that has been base64 encoded, and
  ## as such must be double base64 encoded here.
  OTDS_DIRECTORY_BOOTSTRAP_CRYPTSECRET: {{ required "A valid otdsws.cryptKey is required!" .Values.otds.otdsws.cryptKey | b64enc }}
  ## OTDS_DIRECTORY_BOOTSTRAP_PASSWORD is only required for migrations where there is a need to connect
  ## to an existing otds deployment
  ## OTDS_DB_ADMIN_PASSWORD is the administrative database user (usually postgres for a postgres db or system for an oracle db) password of otds
  OTDS_DB_ADMIN_PASSWORD: {{ default .Values.global.masterPassword .Values.global.passwords.database.adminPassword | b64enc }}
  {{- if and (and (.Values.otds.otdsws.migration.enabled) (not .Values.otds.otdsws.migration.usingLegacyImage) (not .Values.otds.otdsws.migration.preUpgradeJob.enabled)) (not (index $secret "OTDS_DIRECTORY_BOOTSTRAP_PASSWORD"))}}
  OTDS_DIRECTORY_BOOTSTRAP_PASSWORD: {{ default .Values.global.masterPassword .Values.otds.otdsws.migration.password | b64enc }}
  {{- end }}
{{- end }}
{{- if and (eq .Values.global.otpd.enabled true) (not (index $secret "OTPD_ADMIN_PASSWORD")) }}
  ## OTPD_ADMIN_PASSWORD defines the PowerDocs Admin Password (for Tomcat and PowerDocs apps)
  OTPD_ADMIN_PASSWORD: {{ default .Values.global.masterPassword .Values.otpd.adminPassword | b64enc }}
  ## OTPD_USER_PASSWORD defines the PowerDocs User password
  OTPD_USER_PASSWORD: {{ default .Values.global.masterPassword .Values.otpd.userPassword | b64enc }}
  ## OTPD_MONITOR_USER_PASSWORD defines the monitorUser User password
  OTPD_MONITOR_USER_PASSWORD: {{ default .Values.global.masterPassword .Values.otpd.monitorUserPassword | b64enc }}
  ## OTPD_API_USER_PASSWORD defines the apiUser User password
  OTPD_API_USER_PASSWORD: {{ default .Values.global.masterPassword .Values.otpd.apiUserPassword | b64enc }}
  {{- if .Values.otpd.technicalUserPassword }}
  ## OTPD_TECHNICAL_USER_PASSWORD defines the technicalUser User password
  OTPD_TECHNICAL_USER_PASSWORD: {{ .Values.otpd.technicalUserPassword | b64enc }}
  {{- end }}
  ## OTDS_PASSWORD is the administrator password for OTDS
  OTDS_PASSWORD: {{ default .Values.global.masterPassword .Values.otpd.otds.password | b64enc }}
  ## OTCS_ADMIN_PASSWORD is the administrator password for OTCS. This must match ADMIN_USER_PASSWORD above.
  OTCS_ADMIN_PASSWORD: {{ default .Values.global.masterPassword .Values.otpd.otcs.password | b64enc }}
  ## OTPD_DB_ADMIN_PASSWORD is the admin password that is required for database connection for PowerDocs
  OTPD_DB_ADMIN_PASSWORD: {{ default .Values.global.masterPassword .Values.otpd.database.adminPassword | b64enc }}
  ## OTPD_DB_PASSWORD is the user password that is required for database connection for PowerDocs
  OTPD_DB_PASSWORD: {{ default .Values.global.masterPassword .Values.otpd.database.password | b64enc }}
  {{- if .Values.otpd.emailServerSettings.password }}
  ## EMAIL_SERVER_PASSWORD is the password for email server
  EMAIL_SERVER_PASSWORD: {{ .Values.otpd.emailServerSettings.password | b64enc }}
  {{- end }}
{{- end }}
{{- if (.Values.global.otiv.enabled) }}
  ## OTIV_DB_ADMIN_PASSWORD is the db admin password used by OTIV to create and initialize the OTIV database
  OTIV_DB_ADMIN_PASSWORD: {{ default .Values.global.masterPassword .Values.global.passwords.database.adminPassword | b64enc }}
  ## OTIV_DB_PASSWORD is the db password used by the OTIV services db user to connect with the OTIV database
  OTIV_DB_PASSWORD: {{ default .Values.global.masterPassword .Values.global.passwords.database.ivPassword | b64enc }}
{{- if and ( .Values.otiv.amqp.enabled ) (not (index $secret "rabbitmq-password")) }}
  rabbitmq-password: {{ default .Values.global.masterPassword .Values.global.amqp.password | b64enc }}
{{- end }}
{{- if and ( .Values.otiv.publication.enabled ) (not (index $secret "OTIV_PUBLICATION_CLIENT_SECRET")) }}
  OTIV_PUBLICATION_CLIENT_SECRET: {{ default (randAlphaNum 16 | nospace) .Values.otiv.publication.clientSecret | b64enc }}
{{- end }}
{{- if and ( .Values.otiv.publication.enabled ) (not (index $secret "OTIV_MONITOR_CLIENT_SECRET")) }}
  OTIV_MONITOR_CLIENT_SECRET: {{ default (randAlphaNum 16 | nospace) .Values.otiv.publication.monitoring.clientSecret | b64enc }}
{{- end }}
{{- if and ( .Values.otiv.publisher.enabled ) (not (index $secret "OTIV_PUBLISHER_CLIENT_SECRET")) }}
  OTIV_PUBLISHER_CLIENT_SECRET: {{ default (randAlphaNum 16 | nospace) .Values.otiv.publisher.clientSecret | b64enc }}
{{- end }}
{{- if and ( .Values.otiv.highlight.enabled ) (not (index $secret "OTIV_HIGHLIGHT_CLIENT_SECRET")) }}
  OTIV_HIGHLIGHT_CLIENT_SECRET: {{ default (randAlphaNum 16 | nospace) .Values.otiv.highlight.clientSecret | b64enc }}
{{- end }}
{{- if  not (index $secret "OTIV_CS_CLIENT_SECRET") }}
  OTIV_CS_CLIENT_SECRET: {{ default (randAlphaNum 16 | nospace) .Values.otiv.otcs.clientSecret | b64enc }}
{{- end }}
{{- end }}
{{- end }}
